title: PolicyEngine Core
author: PolicyEngine
copyright: "2022"
logo: logo.png

execute:
  execute_notebooks: off

repository:
  url: https://github.com/policyengine/policyengine-core
  branch: master
  path_to_book: docs

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.js
    html_theme: furo
    pygments_style: default
    html_css_files:
      - style.css
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinxarg.ext"
    - "sphinx.ext.viewcode"
    - "sphinx.ext.napoleon"
    - "sphinx_math_dollar"
    - "sphinx.ext.mathjax"
